'use client'

import { useState, useTransition, useCallback } from 'react'
import { useRouter } from 'next/navigation'
import { useTranslations } from 'next-intl'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import {
	AlertDialog,
	AlertDialogAction,
	AlertDialogCancel,
	AlertDialogContent,
	AlertDialogDescription,
	AlertDialogFooter,
	AlertDialogHeader,
	AlertDialogTitle,
	AlertDialogTrigger,
} from '@/components/ui/alert-dialog'
import { useActionError } from '@/hooks/use-action-error'
import { createMarket, updateMarket, deleteMarket } from '../actions'

interface Market {
	id: string
	name: string
	slug: string
	code: string
	flagEmoji: string | null
	sortOrder: number
	created_at: string
	creatorCount: number
}

interface MarketsListProps {
	markets: Market[]
}

export function MarketsList({ markets }: MarketsListProps) {
	const t = useTranslations('admin')
	const router = useRouter()
	const [isPending, startTransition] = useTransition()
	const [error, setError] = useState<string | null>(null)
	const [editingId, setEditingId] = useState<string | null>(null)
	const [showAdd, setShowAdd] = useState(false)

	const [formName, setFormName] = useState('')
	const [formSlug, setFormSlug] = useState('')
	const [formCode, setFormCode] = useState('')
	const [formFlagEmoji, setFormFlagEmoji] = useState('')
	const [formSortOrder, setFormSortOrder] = useState('0')
	const te = useActionError()

	const resetForm = useCallback(() => {
		setFormName('')
		setFormSlug('')
		setFormCode('')
		setFormFlagEmoji('')
		setFormSortOrder('0')
		setEditingId(null)
		setShowAdd(false)
		setError(null)
	}, [])

	function startEdit(market: Market) {
		setFormName(market.name)
		setFormSlug(market.slug)
		setFormCode(market.code)
		setFormFlagEmoji(market.flagEmoji ?? '')
		setFormSortOrder(String(market.sortOrder))
		setEditingId(market.id)
		setShowAdd(false)
		setError(null)
	}

	function startAdd() {
		resetForm()
		setShowAdd(true)
	}

	function handleSave() {
		setError(null)
		startTransition(async () => {
			const payload = {
				name: formName,
				slug: formSlug || undefined,
				code: formCode,
				flagEmoji: formFlagEmoji || undefined,
				sortOrder: parseInt(formSortOrder, 10) || 0,
			}

			const result = editingId
				? await updateMarket(editingId, payload)
				: await createMarket(payload)

			if (!result.success) {
				setError(te(result.error))
			} else {
				resetForm()
				router.refresh()
			}
		})
	}

	function handleDelete(id: string) {
		setError(null)
		startTransition(async () => {
			const result = await deleteMarket(id)
			if (!result.success) {
				setError(te(result.error))
			} else {
				if (editingId === id) resetForm()
				router.refresh()
			}
		})
	}

	const isFormVisible = showAdd || editingId !== null
	const canSave = formName.trim() && formCode.trim()

	return (
		<div>
			<div className="mb-4 flex items-center justify-between">
				<p className="font-sans text-sm text-muted-foreground">
					{t('marketsDescription')}
				</p>
				<Button
					variant="brand"
					size="sm"
					onClick={startAdd}
					disabled={isPending}
				>
					{t('addMarket')}
				</Button>
			</div>

			{error && (
				<p role="alert" className="mb-4 font-sans text-xs text-destructive">
					{t('marketSaveFailed')}
				</p>
			)}

			{isFormVisible && (
				<Card className="mb-4">
					<CardContent>
						<h2 className="font-heading text-base font-bold tracking-[-0.02em] text-foreground">
							{editingId ? t('editMarket') : t('addMarket')}
						</h2>
						<div className="mt-4 grid gap-4 sm:grid-cols-2">
							<div>
								<Label htmlFor="market-name">{t('marketName')}</Label>
								<Input
									id="market-name"
									value={formName}
									onChange={(e) => setFormName(e.target.value)}
									placeholder={t('marketNamePlaceholder')}
									className="mt-1.5"
								/>
							</div>
							<div>
								<Label htmlFor="market-slug">{t('marketSlug')}</Label>
								<Input
									id="market-slug"
									value={formSlug}
									onChange={(e) => setFormSlug(e.target.value)}
									placeholder={t('marketSlugPlaceholder')}
									className="mt-1.5"
								/>
								<p className="mt-1 font-sans text-xs text-muted-foreground">
									{t('slugAutoGenerated')}
								</p>
							</div>
							<div>
								<Label htmlFor="market-code">{t('marketCode')}</Label>
								<Input
									id="market-code"
									value={formCode}
									onChange={(e) => setFormCode(e.target.value)}
									placeholder={t('marketCodePlaceholder')}
									className="mt-1.5"
								/>
							</div>
							<div className="grid grid-cols-2 gap-4">
								<div>
									<Label htmlFor="market-flag">{t('marketFlagEmoji')}</Label>
									<Input
										id="market-flag"
										value={formFlagEmoji}
										onChange={(e) => setFormFlagEmoji(e.target.value)}
										placeholder={t('marketFlagEmojiPlaceholder')}
										className="mt-1.5"
									/>
								</div>
								<div>
									<Label htmlFor="market-sort">{t('marketSortOrder')}</Label>
									<Input
										id="market-sort"
										type="number"
										value={formSortOrder}
										onChange={(e) => setFormSortOrder(e.target.value)}
										placeholder={t('marketSortOrderPlaceholder')}
										className="mt-1.5"
									/>
								</div>
							</div>
						</div>
						<div className="mt-4 flex gap-2">
							<Button
								variant="brand"
								size="sm"
								onClick={handleSave}
								disabled={isPending || !canSave}
							>
								{isPending ? t('savingAction') : t('saveAction')}
							</Button>
							<Button
								variant="ghost"
								size="sm"
								onClick={resetForm}
								disabled={isPending}
							>
								{t('cancelAction')}
							</Button>
						</div>
					</CardContent>
				</Card>
			)}

			{markets.length === 0 ? (
				<Card>
					<CardContent className="py-12 text-center">
						<p className="font-sans text-sm text-muted-foreground">
							{t('noMarkets')}
						</p>
					</CardContent>
				</Card>
			) : (
				<div className="space-y-2">
					{markets.map((market) => (
						<Card key={market.id}>
							<CardContent className="flex items-center justify-between">
								<div className="min-w-0 flex-1">
									<div className="flex items-center gap-2">
										{market.flagEmoji && (
											<span className="text-lg" aria-hidden="true">
												{market.flagEmoji}
											</span>
										)}
										<h2 className="truncate font-heading text-base font-bold tracking-[-0.02em] text-foreground">
											{market.name}
										</h2>
										<Badge variant="outline">{market.code}</Badge>
									</div>
									<p className="mt-0.5 font-sans text-xs text-muted-foreground">
										{market.slug}
										{' · '}
										{t('creatorsCount', { count: market.creatorCount })}
									</p>
								</div>
								<div className="flex shrink-0 items-center gap-2">
									<Button
										variant="ghost"
										size="sm"
										onClick={() => startEdit(market)}
										disabled={isPending}
									>
										{t('editMarket')}
									</Button>
									<AlertDialog>
										<AlertDialogTrigger asChild>
											<Button
												variant="destructive"
												size="sm"
												disabled={isPending}
											>
												{t('deleteMarket')}
											</Button>
										</AlertDialogTrigger>
										<AlertDialogContent>
											<AlertDialogHeader>
												<AlertDialogTitle>{t('deleteMarket')}</AlertDialogTitle>
												<AlertDialogDescription>
													{t('deleteMarketDescription')}
												</AlertDialogDescription>
											</AlertDialogHeader>
											<AlertDialogFooter>
												<AlertDialogCancel>
													{t('cancelAction')}
												</AlertDialogCancel>
												<AlertDialogAction
													onClick={() => handleDelete(market.id)}
												>
													{t('deleteConfirm')}
												</AlertDialogAction>
											</AlertDialogFooter>
										</AlertDialogContent>
									</AlertDialog>
								</div>
							</CardContent>
						</Card>
					))}
				</div>
			)}
		</div>
	)
}
