'use client'

import { useState, useTransition, useCallback } from 'react'
import { useRouter } from 'next/navigation'
import { useTranslations } from 'next-intl'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import {
	AlertDialog,
	AlertDialogAction,
	AlertDialogCancel,
	AlertDialogContent,
	AlertDialogDescription,
	AlertDialogFooter,
	AlertDialogHeader,
	AlertDialogTitle,
	AlertDialogTrigger,
} from '@/components/ui/alert-dialog'
import { useActionError } from '@/hooks/use-action-error'
import { createSpecialty, updateSpecialty, deleteSpecialty } from '../actions'

interface Specialty {
	id: string
	name: string
	slug: string
	created_at: string
	creatorCount: number
}

interface SpecialtiesListProps {
	specialties: Specialty[]
}

export function SpecialtiesList({ specialties }: SpecialtiesListProps) {
	const t = useTranslations('admin')
	const router = useRouter()
	const [isPending, startTransition] = useTransition()
	const [error, setError] = useState<string | null>(null)
	const [editingId, setEditingId] = useState<string | null>(null)
	const [showAdd, setShowAdd] = useState(false)

	const [formName, setFormName] = useState('')
	const [formSlug, setFormSlug] = useState('')
	const te = useActionError()

	const resetForm = useCallback(() => {
		setFormName('')
		setFormSlug('')
		setEditingId(null)
		setShowAdd(false)
		setError(null)
	}, [])

	function startEdit(specialty: Specialty) {
		setFormName(specialty.name)
		setFormSlug(specialty.slug)
		setEditingId(specialty.id)
		setShowAdd(false)
		setError(null)
	}

	function startAdd() {
		resetForm()
		setShowAdd(true)
	}

	function handleSave() {
		setError(null)
		startTransition(async () => {
			const result = editingId
				? await updateSpecialty(editingId, formName, formSlug || undefined)
				: await createSpecialty(formName, formSlug || undefined)

			if (!result.success) {
				setError(te(result.error))
			} else {
				resetForm()
				router.refresh()
			}
		})
	}

	function handleDelete(id: string) {
		setError(null)
		startTransition(async () => {
			const result = await deleteSpecialty(id)
			if (!result.success) {
				setError(te(result.error))
			} else {
				if (editingId === id) resetForm()
				router.refresh()
			}
		})
	}

	const isFormVisible = showAdd || editingId !== null

	return (
		<div>
			<div className="mb-4 flex items-center justify-between">
				<p className="font-sans text-sm text-muted-foreground">
					{t('specialtiesDescription')}
				</p>
				<Button
					variant="brand"
					size="sm"
					onClick={startAdd}
					disabled={isPending}
				>
					{t('addSpecialty')}
				</Button>
			</div>

			{error && (
				<p role="alert" className="mb-4 font-sans text-xs text-destructive">
					{t('specialtySaveFailed')}
				</p>
			)}

			{isFormVisible && (
				<Card className="mb-4">
					<CardContent>
						<h2 className="font-heading text-base font-bold tracking-[-0.02em] text-foreground">
							{editingId ? t('editSpecialty') : t('addSpecialty')}
						</h2>
						<div className="mt-4 grid gap-4 sm:grid-cols-2">
							<div>
								<Label htmlFor="specialty-name">{t('specialtyName')}</Label>
								<Input
									id="specialty-name"
									value={formName}
									onChange={(e) => setFormName(e.target.value)}
									placeholder={t('specialtyNamePlaceholder')}
									className="mt-1.5"
								/>
							</div>
							<div>
								<Label htmlFor="specialty-slug">{t('specialtySlug')}</Label>
								<Input
									id="specialty-slug"
									value={formSlug}
									onChange={(e) => setFormSlug(e.target.value)}
									placeholder={t('specialtySlugPlaceholder')}
									className="mt-1.5"
								/>
								<p className="mt-1 font-sans text-xs text-muted-foreground">
									{t('slugAutoGenerated')}
								</p>
							</div>
						</div>
						<div className="mt-4 flex gap-2">
							<Button
								variant="brand"
								size="sm"
								onClick={handleSave}
								disabled={isPending || !formName.trim()}
							>
								{isPending ? t('savingAction') : t('saveAction')}
							</Button>
							<Button
								variant="ghost"
								size="sm"
								onClick={resetForm}
								disabled={isPending}
							>
								{t('cancelAction')}
							</Button>
						</div>
					</CardContent>
				</Card>
			)}

			{specialties.length === 0 ? (
				<Card>
					<CardContent className="py-12 text-center">
						<p className="font-sans text-sm text-muted-foreground">
							{t('noSpecialties')}
						</p>
					</CardContent>
				</Card>
			) : (
				<div className="space-y-2">
					{specialties.map((specialty) => (
						<Card key={specialty.id}>
							<CardContent className="flex items-center justify-between">
								<div className="min-w-0 flex-1">
									<div className="flex items-center gap-2">
										<h2 className="truncate font-heading text-base font-bold tracking-[-0.02em] text-foreground">
											{specialty.name}
										</h2>
										<Badge variant="outline">{specialty.slug}</Badge>
									</div>
									<p className="mt-0.5 font-sans text-xs text-muted-foreground">
										{t('creatorsCount', { count: specialty.creatorCount })}
									</p>
								</div>
								<div className="flex shrink-0 items-center gap-2">
									<Button
										variant="ghost"
										size="sm"
										onClick={() => startEdit(specialty)}
										disabled={isPending}
									>
										{t('editSpecialty')}
									</Button>
									<AlertDialog>
										<AlertDialogTrigger asChild>
											<Button
												variant="destructive"
												size="sm"
												disabled={isPending}
											>
												{t('deleteSpecialty')}
											</Button>
										</AlertDialogTrigger>
										<AlertDialogContent>
											<AlertDialogHeader>
												<AlertDialogTitle>
													{t('deleteSpecialty')}
												</AlertDialogTitle>
												<AlertDialogDescription>
													{t('deleteSpecialtyDescription')}
												</AlertDialogDescription>
											</AlertDialogHeader>
											<AlertDialogFooter>
												<AlertDialogCancel>
													{t('cancelAction')}
												</AlertDialogCancel>
												<AlertDialogAction
													onClick={() => handleDelete(specialty.id)}
												>
													{t('deleteConfirm')}
												</AlertDialogAction>
											</AlertDialogFooter>
										</AlertDialogContent>
									</AlertDialog>
								</div>
							</CardContent>
						</Card>
					))}
				</div>
			)}
		</div>
	)
}
